In [8]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('heart.csv')
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [4]:
data.isnull().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [5]:
X = data.iloc[:,:13].values
y = data["target"].values

In [9]:
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size = 0.3 , random_state = 0 )
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
classifier = Sequential()
classifier.add(Dense(activation = "relu", input_dim = 13,
units = 8, kernel_initializer = "uniform"))
classifier.add(Dense(activation = "relu", units = 14,
kernel_initializer = "uniform"))
classifier.add(Dense(activation = "sigmoid", units = 1,
kernel_initializer = "uniform"))
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy',
metrics = ['accuracy'] )
classifier.fit(X_train , y_train , batch_size = 8 ,epochs = 100 )

Epoch 1/100
27/27 [==============================] - 2s 2ms/step - loss: 0.6927 - accuracy: 0.5519
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6896 - accuracy: 0.6415
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6773 - accuracy: 0.8019
Epoch 4/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6434 - accuracy: 0.8491
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5771 - accuracy: 0.8491
Epoch 6/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4952 - accuracy: 0.8538
Epoch 7/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4245 - accuracy: 0.8585
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3803 - accuracy: 0.8679
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3550 - accuracy: 0.8679
Epoch 10/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3420 - accuracy: 0.8632
Epoch 11/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8679
Epoch 12/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3275 - accuracy: 0.8632
Epoch 13/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8726
Epoch 14/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3200 - accuracy: 0.8774
Epoch 15/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3176 - accuracy: 0.8821
Epoch 16/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3154 - accuracy: 0.8868
Epoch 17/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3128 - accuracy: 0.8868
Epoch 18/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3115 - accuracy: 0.8868
Epoch 19/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3097 - accuracy: 0.8774
Epoch 20/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3064 - accuracy: 0.8821
Epoch 21/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3049 - accuracy: 0.8868
Epoch 22/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3038 - accuracy: 0.8821
Epoch 23/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3028 - accuracy: 0.8868
Epoch 24/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3012 - accuracy: 0.8868
Epoch 25/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2999 - accuracy: 0.8868
Epoch 26/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2990 - accuracy: 0.8868
Epoch 27/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2976 - accuracy: 0.8774
Epoch 28/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2976 - accuracy: 0.8774
Epoch 29/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2955 - accuracy: 0.8821
Epoch 30/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2939 - accuracy: 0.8726
Epoch 31/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2935 - accuracy: 0.8821
Epoch 32/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2922 - accuracy: 0.8821
Epoch 33/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2907 - accuracy: 0.8821
Epoch 34/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2889 - accuracy: 0.8821
Epoch 35/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2896 - accuracy: 0.8821
Epoch 36/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2892 - accuracy: 0.8868
Epoch 37/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2859 - accuracy: 0.8774
Epoch 38/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2856 - accuracy: 0.8821
Epoch 39/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2850 - accuracy: 0.8774
Epoch 40/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 0.8821
Epoch 41/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 0.8821
Epoch 42/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2810 - accuracy: 0.8868
Epoch 43/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2822 - accuracy: 0.8868
Epoch 44/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2790 - accuracy: 0.8774
Epoch 45/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2792 - accuracy: 0.8774
Epoch 46/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2784 - accuracy: 0.8868
Epoch 47/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2768 - accuracy: 0.8868
Epoch 48/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2760 - accuracy: 0.8821
Epoch 49/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2752 - accuracy: 0.8868
Epoch 50/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2742 - accuracy: 0.8915
Epoch 51/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2731 - accuracy: 0.8821
Epoch 52/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2723 - accuracy: 0.8868
Epoch 53/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2711 - accuracy: 0.8868
Epoch 54/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2702 - accuracy: 0.8915
Epoch 55/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2701 - accuracy: 0.8868
Epoch 56/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2709 - accuracy: 0.8868
Epoch 57/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2680 - accuracy: 0.8915
Epoch 58/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2668 - accuracy: 0.8915
Epoch 59/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2679 - accuracy: 0.8868
Epoch 60/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2651 - accuracy: 0.8915
Epoch 61/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2639 - accuracy: 0.8962
Epoch 62/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2635 - accuracy: 0.8915
Epoch 63/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2621 - accuracy: 0.8915
Epoch 64/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2614 - accuracy: 0.9009
Epoch 65/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2614 - accuracy: 0.9009
Epoch 66/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2593 - accuracy: 0.9009
Epoch 67/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2584 - accuracy: 0.9009
Epoch 68/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2572 - accuracy: 0.9057
Epoch 69/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2563 - accuracy: 0.9057
Epoch 70/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2560 - accuracy: 0.8962
Epoch 71/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2547 - accuracy: 0.9057
Epoch 72/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2536 - accuracy: 0.9151
Epoch 73/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2529 - accuracy: 0.9057
Epoch 74/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2523 - accuracy: 0.9057
Epoch 75/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2509 - accuracy: 0.9104
Epoch 76/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2496 - accuracy: 0.9151
Epoch 77/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2483 - accuracy: 0.9104
Epoch 78/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2475 - accuracy: 0.9104
Epoch 79/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2464 - accuracy: 0.9151
Epoch 80/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2446 - accuracy: 0.9198
Epoch 81/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2440 - accuracy: 0.9198
Epoch 82/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2429 - accuracy: 0.9151
Epoch 83/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2416 - accuracy: 0.9151
Epoch 84/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2413 - accuracy: 0.9151
Epoch 85/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2392 - accuracy: 0.9151
Epoch 86/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2376 - accuracy: 0.9151
Epoch 87/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2372 - accuracy: 0.9198
Epoch 88/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2348 - accuracy: 0.9245
Epoch 89/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2347 - accuracy: 0.9198
Epoch 90/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2337 - accuracy: 0.9245
Epoch 91/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2325 - accuracy: 0.9198
Epoch 92/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2308 - accuracy: 0.9151
Epoch 93/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2305 - accuracy: 0.9198
Epoch 94/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2290 - accuracy: 0.9198
Epoch 95/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2282 - accuracy: 0.9245
Epoch 96/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2265 - accuracy: 0.9292
Epoch 97/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2257 - accuracy: 0.9245
Epoch 98/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2241 - accuracy: 0.9245
Epoch 99/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2234 - accuracy: 0.9198
Epoch 100/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2214 - accuracy: 0.9292

In [11]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test,y_pred)
cm

3/3 [==============================] - 0s 4ms/step

array([[35,  9],
       [ 4, 43]])

In [12]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1])
print(accuracy*100)

85.71428571428571